In [45]:
# 1.3.1 A feed-forward example adding matricies- pg 15
# Note that the weights aren't randomly generated because this is a really basic example
import numpy as np

In [46]:
w1 = np.array([[0.2, 0.2, 0.2],
                [0.4, 0.4, 0.4],
                [0.6, 0.6, 0.6]])

w2 = np.zeros((1,3))
w2[0,:] = np.array([0.5, 0.5, 0.5])

b1 = np.array([0.8, 0.8, 0.8])
b2 = np.array([0.2])

In [47]:
w = [w1, w2]
b = [b1, b2]
#a dummy x input vector
x = [1.5, 2.0, 3.0]

In [48]:
# Activation Function (Sigmoid)
def f(x):
    return 1/ (1 + np.exp(-x))

In [49]:
def matrix_feed_forward_calc(n_layers, x, w, b):
    for l in range(n_layers-1):
        if l == 0:
            node_in = x
        else:
            node_in = h
        z = w[l].dot(node_in) + b[l]
        h = f(z)
    return h

In [50]:
print(matrix_feed_forward_calc(3,x,w,b))

[0.83545566]


In [51]:
%timeit matrix_feed_forward_calc(3,x,w,b)

8.96 µs ± 150 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Note: The below is to better understand what the network is doing - this can be ignored

In [63]:
w

[array([[0.2, 0.2, 0.2],
        [0.4, 0.4, 0.4],
        [0.6, 0.6, 0.6]]), array([[0.5, 0.5, 0.5]])]

In [64]:
b

[array([0.8, 0.8, 0.8]), array([0.2])]

In [65]:
x

[1.5, 2.0, 3.0]

In [54]:
m = w[0].dot(x) + b[0]
m

array([2.1, 3.4, 4.7])

In [55]:
f(m)

array([0.89090318, 0.96770454, 0.9909867 ])

In [57]:
n = w[1].dot(f(m)) + b[1]
n

array([1.62479721])

In [59]:
f(n)

array([0.83545566])